# Name of our action
name: Release

# The event that will trigger the action
on:
  push:
    branches: [develop]

jobs:
  install:
    name: Installing Packges
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Cache node_modules
       uses: actions/checkout@v2
       with:
        path: node_modules
        key: yarn-deps-${{ hashFiles('yarn.lock') }}
        restore-keys: |
        yarn-deps-${{ hashFiles('yarn.lock') }}
        github_actor: ${{ github.actor }}

     - name: Install dependencies
       run: yarn install
